email: "brcopeland@ucsd.edu"
#reference files - don't change unless you have a good reason to do so, change genome_build variable instead
reference:
        hg38:
                genome: "../resources/Homo_sapiens_assembly38.fasta"
                dbsnp: "../resources/Homo_sapiens_assembly38.dbsnp138.vcf"
                indel_mills: "../resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
                indel_known: "../resources/Homo_sapiens_assembly38.known_indels.vcf.gz"
