genome_build: {{cookiecutter.genome_build}}
sequencing_type: {{cookiecutter.sequencing_type}}
email: {{cookiecutter.email}}

# program parameters
bwa:
  K: 100000000 # suggested for reproducibility
  Y: "" # soft-clipping of supplementary alignments
haplotype_caller:
  annotation-group: [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
genotype_gvcfs:
  annotation-group: [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
  only-output-calls-starting-in-intervals: ""
snp_recalibration:
  use-allele-specific-annotations: ""
  $((SNP_GAUSSIANS))# N.B. we use 2 max-gaussians for WES and don't specify for WGS
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.8, 99.6, 99.5, 99.4, 99.3, 99.0, 98.0, 97.0, 90.0]
  resources:
    hapmap: {known: False, training: True, truth: True, prior: 15.0}
    omni: {known: False, training: True, truth: False, prior: 12.0}
    onekg: {known: False, training: True, truth: False, prior: 10.0}
    dbsnp: {known: True, training: False, truth: False, prior: 2.0}
  annotation: [QD, MQ, MQRankSum, ReadPosRankSum, FS, SOR, InbreedingCoeff$((DP))] # N.B. you should use DP with WGS and should NOT use DP with WES
apply_snp_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-filter-level: 99.7
indel_recalibration:
  use-allele-specific-annotations: ""
  max-gaussians: $((INDEL_GAUSSIANS)) # N.B. we use 2 max-gaussians for WES and 4 for WGS
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.5, 99.0, 97.0, 96.0, 95.0, 94.0, 93.5, 93.0, 92.0, 91.0, 90.0]
  resources:
    mills: {known: False, training: True, truth: True, prior: 12.0}
    axiom: {known: False, training: True, truth: False, prior: 10.0}
    dbsnp: {known: True, training: False, truth: False, prior: 2.0}
  annotation: [QD, FS, SOR, ReadPosRankSum, MQRankSum, InbreedingCoeff$((DP))] # N.B. you should use DP with WGS and should NOT use DP with WES
apply_indel_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-filter-level: 99.0
mosdepth:
  fast-mode: ""
  no-per-base: ""
  thresholds: [20, 30, 60, 100, 200]
somalier:
  url: github.com/brentp/somalier/releases/download/v0.2.13/somalier # not available via conda (currently)
max_contamination: {{cookiecutter.max_intraspecies_contamination}} # maximum tolerable intra-species contamination
min_relatedness: {{cookiecutter.min_identity_relatedness}} # minimum tolerable relatedness for two read groups from same individual
cryptic_relatedness_threshold: 0.2 # flag any pair of samples labeled as coming from different families with greater than this relatedness
intra_family_cryptic_relatedness_threshold: 0.3 # flag any pair of samples from the same family but not documented as being siblings nor parent-child
first_degree_relatedness: {min: 0.4, max: 0.6}
sex_check_threshold: 0.6 # above is considered female, below male
create_interval_files: # stores MB to use for interval files
  exome: 100
  genome: 30

#reference files - don't change unless you have a good reason to do so, change genome_build variable instead
# This is all designed to use downloadable resources from public sources.  The code requires no leading http:// or https:// prefix and is not designed for running on local files.
reference:
  hg38:
    axiom: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
    axiom_idx: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz.tbi
    fasta: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
    fasta_dict: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dict
    fasta_idx: [storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.alt, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.amb, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.ann, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.bwt, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.pac, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.sa, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.amb, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.ann, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.bwt, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.pac, storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.sa]
    dbsnp: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.gz
    dbsnp_idx: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi
    hapmap: storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/hapmap_3.3.hg38.vcf.gz
    #hapmap_idx: storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/hapmap_3.3.hg38.vcf.gz.tbi
    indel_known: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.known_indels.vcf.gz
    #indel_known_idx: storage.cloud.google.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.known_indels.vcf.gz.tbi
    indel_mills: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    #indel_mills_idx: storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi
    omni: storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_omni2.5.hg38.vcf.gz
    omni_idx: storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_omni2.5.hg38.vcf.gz.tbi
    onekg: storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz
    onekg_idx: storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi
    exome:
      bed: ../resources/hg38/CCDS.hg38.bed
    genome:
      bed: ../resources/hg38/Homo_sapiens_assembly38.bed
    somalier_sites: github.com/brentp/somalier/files/3412456/sites.hg38.vcf.gz
  hg19:
    axiom: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.vcf.gz
    axiom_idx: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.vcf.gz.tbi
    fasta: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta
    fasta_dict: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.dict
    fasta_idx: [storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.64.amb, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.64.ann, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.64.bwt, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.64.pac, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.64.sa, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.alt, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.amb, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.ann, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.bwt, storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.fai]
    dbsnp: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.dbsnp138.vcf
    dbsnp_idx: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.dbsnp138.vcf.idx
    hapmap: storage.googleapis.com/gatk-legacy-bundles/b37/hapmap_3.3.b37.vcf.gz
    indel_known: storage.googleapis.com/gatk-legacy-bundles/b37/1000G_phase1.indels.b37.vcf.gz
    indel_mills: storage.googleapis.com/gatk-legacy-bundles/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
    omni: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/1000G_omni2.5.b37.vcf.gz
    omni_idx: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/1000G_omni2.5.b37.vcf.gz.tbi
    onekg: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/1000G_phase1.snps.high_confidence.b37.vcf.gz
    onekg_idx: storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/1000G_phase1.snps.high_confidence.b37.vcf.gz
    exome:
      bed: ../resources/grch37/CCDS.grch37.bed
    genome:
      bed: ../resources/grch37/human_g1k_v37_decoy.bed
    somalier_sites: github.com/brentp/somalier/files/3412455/sites.GRCh37.vcf.gz
