genome_build: {{cookiecutter.genome_build}}
sequencing_type: {{cookiecutter.sequencing_type}}
ploidy: &ploidy {{cookiecutter.ploidy}}
email: {{cookiecutter.email}}
sample_regex: '[a-zA-Z\d_-]+' # sample identifiers must match this

# program parameters
vqsr:
  max_gaussians:
    snp:
      genome: &max_gaussians_snp_genome 8
      other: &max_gaussians_snp_other 2
    indel:
      genome: &max_gaussians_indel_genome 4
      other: &max_gaussians_indel_other 2
  extra_annotations: # additional annotations used by sequencing type
    genome: [DP] # use DP for WGS, not for others
    exome: []
    amplicon: []
  # additional joint-genotyping annotations used type if samples are diploid
  extra_joint_diploid_annotations: [InbreedingCoeff]
bwa:
  K: 100000000 # suggested for reproducibility
  Y: # soft-clipping of supplementary alignments
haplotype_caller:
  annotation-group: &annotation_group [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
  ploidy: *ploidy
genotype_gvcfs:
  annotation-group: *annotation_group
  ? only-output-calls-starting-in-intervals
snp_recalibration:
  ? use-allele-specific-annotations
  max_gausians: $((SNP_GAUSSIANS))
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.8, 99.6, 99.5, 99.4, 99.3, 99.0, 98.0, 97.0, 90.0]
  resources:
    hapmap: {known: False, training: True, truth: True, prior: 15.0}
    omni: {known: False, training: True, truth: False, prior: 12.0}
    onekg: {known: False, training: True, truth: False, prior: 10.0}
    dbsnp: {known: True, training: False, truth: False, prior: 2.0}
  annotation: [FS, MQ, MQRankSum, QD, ReadPosRankSum, SOR]
apply_snp_recalibration:
  ? use-allele-specific-annotations
  truth-sensitivity-filter-level: 99.7
indel_recalibration:
  ? use-allele-specific-annotations
  max-gaussians: $((INDEL_GAUSSIANS))
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.5, 99.0, 97.0, 96.0, 95.0, 94.0, 93.5, 93.0, 92.0, 91.0, 90.0]
  resources:
    mills: {known: False, training: True, truth: True, prior: 12.0}
    axiom: {known: False, training: True, truth: False, prior: 10.0}
    dbsnp: {known: True, training: False, truth: False, prior: 2.0}
  annotation: [FS, MQRankSum, QD, ReadPosRankSum, SOR]
apply_indel_recalibration:
  ? use-allele-specific-annotations
  truth-sensitivity-filter-level: 99.0
mosdepth:
  ? fast-mode
  ? no-per-base
  thresholds: [20, 30, 60, 100, 200]
max_contamination: {{cookiecutter.max_intraspecies_contamination}} # maximum tolerable intra-species contamination
min_relatedness: {{cookiecutter.min_identity_relatedness}} # minimum tolerable relatedness for two read groups from same individual
cryptic_relatedness_threshold: 0.2 # flag any pair of samples labeled as coming from different families with greater than this relatedness
intra_family_cryptic_relatedness_threshold: 0.3 # flag any pair of samples from the same family but not documented as being siblings nor parent-child
first_degree_relatedness: {min: 0.4, max: 0.6}
sex_check_threshold: 0.6 # X chromosome het/hom ratio: above is considered female, below male
create_interval_files: # stores MB to use for interval files
  amplicon: 4000 # use the entire genome
  exome: 100
  genome: 30
resources_repository: {{cookiecutter.resources_repository}}

#reference files - don't change unless you have a good reason to do so, change genome_build variable instead
reference:
  hg38:
    axiom: ../resources/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
    fasta: ../resources/Homo_sapiens_assembly38.fasta
    fasta_dict: ../resources/Homo_sapiens_assembly38.dict
    dbsnp: ../resources/Homo_sapiens_assembly38.dbsnp138.vcf
    hapmap: ../resources/hapmap_3.3.hg38.vcf.gz
    indel_mills: ../resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    indel_known: ../resources/Homo_sapiens_assembly38.known_indels.vcf.gz
    omni: ../resources/1000G_omni2.5.hg38.vcf.gz
    onekg: ../resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz
    amplicon:
      bed: &hg38_ccds_bed ../resources/CCDS.hg38.bed
    exome:
      bed: *hg38_ccds_bed
    genome:
      bed: ../resources/Homo_sapiens_assembly38.bed
  grch37:
    axiom: ../resources/Axiom_Exome_Plus.genotypes.all_populations.vcf.gz
    fasta: ../resources/human_g1k_v37_decoy.fasta
    fasta_dict: ../resources/human_g1k_v37_decoy.dict
    dbsnp: ../resources/dbsnp_138.b37.vcf
    hapmap: ../resources/hapmap_3.3.b37.sites.vcf
    indel_mills: ../resources/Mills_and_1000G_gold_standard.indels.b37.sites.vcf
    indel_known: ../resources/1000G_phase1.indels.b37.vcf
    omni: ../resources/1000G_omni2.5.b37.sites.vcf
    onekg: ../resources/1000G_phase1.snps.high_confidence.b37.sites.vcf
    amplicon:
      bed: &grch37_ccds_bed ../resources/CCDS.grch37.bed
    exome:
      bed: *grch37_ccds_bed
    genome:
      bed: ../resources/human_g1k_v37_decoy.bed
