#reference files - don't change unless you have a good reason to do so, change genome_build variable instead
reference:
  hg38:
    axiom: ../resources/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
    genome: ../resources/Homo_sapiens_assembly38.fasta
    genome_dict: ../resources/Homo_sapiens_assembly38.dict
    dbsnp: ../resources/Homo_sapiens_assembly38.dbsnp138.vcf
    hapmap: ../resources/hapmap_3.3.hg38.vcf.gz
    indel_mills: ../resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    indel_known: ../resources/Homo_sapiens_assembly38.known_indels.vcf.gz
    omni: ../resources/1000G_omni2.5.hg38.vcf.gz
    onekg: ../resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz
bwa:
  K: 100000000 # suggested for reproducibility
  Y: "" # soft-clipping of supplementary alignments
haplotype_caller:
  annotation-group: [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
genotype_gvcfs:
  annotation-group: [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
  only-output-calls-starting-in-intervals: ""
snp_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.8, 99.6, 99.5, 99.4, 99.3, 99.0, 98.0, 97.0, 90.0]
apply_snp_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-filter-level: 99.7
indel_recalibration:
  use-allele-specific-annotations: ""
  max-gaussians: 4
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.5, 99.0, 97.0, 96.0, 95.0, 94.0, 93.5, 93.0, 92.0, 91.0, 90.0]
apply_indel_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-filter-level: 99.0
