#reference files - don't change unless you have a good reason to do so, change genome_build variable instead
reference:
  hg38:
    axiom: ../resources/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
    genome: ../resources/Homo_sapiens_assembly38.fasta
    genome_dict: ../resources/Homo_sapiens_assembly38.dict
    dbsnp: ../resources/Homo_sapiens_assembly38.dbsnp138.vcf
    hapmap: ../resources/hapmap_3.3.hg38.vcf.gz
    indel_mills: ../resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    indel_known: ../resources/Homo_sapiens_assembly38.known_indels.vcf.gz
    omni: ../resources/1000G_omni2.5.hg38.vcf.gz
    onekg: ../resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz
  grch37:
    axiom: ../resources/Axiom_Exome_Plus.genotypes.all_populations.vcf.gz
    genome: ../resources/human_g1k_v37_decoy.fasta
    genome_dict: ../resources/human_g1k_v37_decoy.dict
    dbsnp: ../resources/dbsnp_138.b37.vcf
    hapmap: ../resources/hapmap_3.3.b37.sites.vcf
    indel_mills: ../resources/Mills_and_1000G_gold_standard.indels.b37.sites.vcf
    indel_known: ../resources/1000G_phase1.indels.b37.vcf
    omni: ../resources/1000G_omni2.5.b37.sites.vcf
    onekg: ../resources/1000G_phase1.snps.high_confidence.b37.sites.vcf

bwa:
  K: 100000000 # suggested for reproducibility
  Y: "" # soft-clipping of supplementary alignments
haplotype_caller:
  annotation-group: [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
genotype_gvcfs:
  annotation-group: [StandardAnnotation, AS_StandardAnnotation, StandardHCAnnotation]
  only-output-calls-starting-in-intervals: ""
snp_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.8, 99.6, 99.5, 99.4, 99.3, 99.0, 98.0, 97.0, 90.0]
  resources:
    hapmap: {known: False, training: True, truth: True, prior: 15.0}
    omni: {known: False, training: True, truth: False, prior: 12.0}
    onekg: {known: False, training: True, truth: False, prior: 10.0}
    dbsnp: {known: True, training: False, truth: False, prior: 2.0}
  annotation: [QD, MQ, MQRankSum, ReadPosRankSum, FS, SOR, InbreedingCoeff$((DP))] # N.B. you should use DP with WGS and should NOT use DP with WES
apply_snp_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-filter-level: 99.7
indel_recalibration:
  use-allele-specific-annotations: ""
  max-gaussians: 4
  truth-sensitivity-tranche: [100.0, 99.95, 99.9, 99.5, 99.0, 97.0, 96.0, 95.0, 94.0, 93.5, 93.0, 92.0, 91.0, 90.0]
  resources:
    mills: {known: False, training: True, truth: True, prior: 12.0}
    axiom: {known: False, training: True, truth: False, prior: 10.0}
    dbsnp: {known: True, training: False, truth: False, prior: 2.0}
  annotation: [QD, FS, SOR, ReadPosRankSum, MQRankSum, InbreedingCoeff$((DP))] # N.B. you should use DP with WGS and should NOT use DP with WES
apply_indel_recalibration:
  use-allele-specific-annotations: ""
  truth-sensitivity-filter-level: 99.0
